### ISSUE TITLE
Visual Studio 2019 Compatibility

### ISSUE THREAD

**Issue by motivity-chris** [Predelnik/RemoveTrailingWhitespaces#1]
This extension is very useful, but I am finding that it doesn't appear to be compatible with Visual Studio 2019 Preview.

Are there any plans to update the project to work with 2019?

**Comment by Predelnik** [comment]
Sorry for auto-closing the issue.
I had some trouble with updating so I decided to make separate upload on marketplace (which supports only 2019 for now), it should have exactly the same functionality, icons and so on. But it may still a bit unfortunate since all the ratings / comments etc. is gone.

Anyway here it is:
https://marketplace.visualstudio.com/items?itemName=Predelnik.RemoveTrailingWhitespaces2019

I would be very glad if you check that it works you, to be honest updating VS extensions always seems painful for me even for simple one such as this. Keeping them compatible with older VS versions is even more work.

**Comment by motivity-chris** [comment]
Thanks -- works for me!

**Comment by wesj1s** [comment]
Hi, thanks for your time in creating and maintaining this extension. It works great except that it also deletes trailing whitespace in multi-line strings. These are often necessary in places like unit tests. I've found that all the similar extensions do the same thing! If there was a way to treat trailing whitespaces within a multiline string differently, and allow them to not be deleted, that would be perfection! Cheers.

**Comment by Predelnik** [comment]
@wesj1s I understand why this could be problematic, probably won't be an easy fix because multi-line strings specified differently in different programming languages but I might look into it. It'd be nice to create a separate issue however.

**Comment by Predelnik** [comment]
Would close this issue to be less confusing, with creating separate issue about multi-line strings.
